version: '3.7'
services:
  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
  app:
    build: .
    environment:
      DB_URI: mongodb://root:rootpassword@mongo/db
      TOKEN_SECRET: secret
    ports: 
      - 3000:3000