service: serverless
# app and org for use with dashboard.serverless.com
#app: ccr-team92
#org: ccr-team92

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1

  environment:
    DB_URI: ${file(config.${opt:stage, self:provider.stage, 'dev'}.json):DB_URI}

plugins:
  - serverless-webpack
  - serverless-offline

functions:
  debug:
    handler: src/endpoints/debug.endpoint
    events:
      - httpApi:
          path: /debug
          method: get
  users_list:
    handler: src/endpoints/users.list
    events:
      - httpApi:
          path: /users
          method: get

custom:
  webpack:
    webpackConfig: 'webpack.config.js'
    includeModules: false
    packager: 'yarn'
    excludeFiles: test/**/*.js