service: serverless
# app: ccrteam92
# org: ccrteam92

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  apiGateway:
    shouldStartNameWithService: true

  stage: dev
  region: us-east-1

  environment:
    DB_URI: ${file(config.${opt:stage, self:provider.stage, 'dev'}.json):DB_URI}

plugins:
  - serverless-webpack
  - serverless-offline

functions:
  debug:
    handler: src/debug.endpoint
    events:
      - httpApi:
          path: /debug
          method: get
  app:
    handler: src/index.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{any+}
          method: ANY

custom:
  webpack:
    webpackConfig: 'webpack.config.js'
    includeModules: false
    packager: 'yarn'
    excludeFiles: test/**/*.js
  serverless-offline:
    noPrependStageInUrl: true